### Test for /get_recipes endpoint
POST http://127.0.0.1:5000/get_recipes
Content-Type: application/json

{
  "ingredients": [ "lettuce", "tomato", "cheese"]
}

### Test for /filter_ingredients endpoint
POST http://127.0.0.1:5000/filter_ingredients
Content-Type: application/json

{
  "ingredients": ["tomato", "cheese", "tomato", "garlic", "Flugzeugteil45678"]
}
