openapi: '3.0.3'
info:
  title: Recipe API
  version: '1.0'
servers:
  - url: http://127.0.0.1:5000
paths:
  /filter_ingredients:
    post:
      summary: Filter data to recipes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ingredients:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  filtered_ingredients:
                    type: string
                    example: "Tomaten, Salat"
        
  /get_recipes:
    post:
      summary: Get recipes from ingredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ingredients:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  recipes:
                    type: object
                    properties:
                      rezepte:
                        type: array
                        items:
                          type: object
                          properties:
                            allergies:
                              type: array
                              items:
                                type: string
                            healthy:
                              type: boolean
                            hotOrCold:
                              type: string
                            name:
                              type: string
                            howToCook:
                              type: string
                            ingredients:
                              type: array
                              items:
                                type: string

  /get_additional_ingredients: 
    post:
      summary: Get additional ingredients for recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipe:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  additional_ingredients:
                    type: array
                    items:
                      type: string
